export const CONTRACT_ADDRESS = "0x33A71e83A76bA83E77A3078237F7ae1B919FDC89";

export const CONTRACT_ABI = [
  { "inputs": [], "stateMutability": "nonpayable", "type": "constructor" },
  { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "uint256", "name": "playerId", "type": "uint256" }, { "indexed": false, "internalType": "string", "name": "name", "type": "string" }, { "indexed": false, "internalType": "string", "name": "position", "type": "string" }, { "indexed": false, "internalType": "uint256", "name": "basePrice", "type": "uint256" }], "name": "PlayerRegistered", "type": "event" },
  { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "uint256", "name": "auctionId", "type": "uint256" }, { "indexed": true, "internalType": "uint256", "name": "playerId", "type": "uint256" }, { "indexed": false, "internalType": "uint256", "name": "endTime", "type": "uint256" }], "name": "AuctionCreated", "type": "event" },
  { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "uint256", "name": "auctionId", "type": "uint256" }, { "indexed": true, "internalType": "address", "name": "bidder", "type": "address" }, { "indexed": false, "internalType": "uint256", "name": "bidAmount", "type": "uint256" }], "name": "BidPlaced", "type": "event" },
  { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "uint256", "name": "auctionId", "type": "uint256" }, { "indexed": true, "internalType": "address", "name": "winner", "type": "address" }, { "indexed": false, "internalType": "uint256", "name": "winningBid", "type": "uint256" }], "name": "AuctionEnded", "type": "event" },
  { "inputs": [], "name": "admin", "outputs": [{ "internalType": "address", "name": "", "type": "address" }], "stateMutability": "view", "type": "function" },
  { "inputs": [], "name": "playerCount", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" },
  { "inputs": [], "name": "auctionCount", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" },
  { "inputs": [{ "internalType": "uint256", "name": "_playerId", "type": "uint256" }], "name": "getPlayer", "outputs": [{ "components": [{ "internalType": "uint256", "name": "id", "type": "uint256" }, { "internalType": "string", "name": "name", "type": "string" }, { "internalType": "string", "name": "position", "type": "string" }, { "internalType": "uint256", "name": "basePrice", "type": "uint256" }, { "internalType": "address", "name": "currentClub", "type": "address" }, { "internalType": "bool", "name": "auctioned", "type": "bool" }], "internalType": "struct PlayerAuction.Player", "name": "", "type": "tuple" }], "stateMutability": "view", "type": "function" },
  { "inputs": [{ "internalType": "uint256", "name": "_auctionId", "type": "uint256" }], "name": "getAuction", "outputs": [{ "components": [{ "internalType": "uint256", "name": "playerId", "type": "uint256" }, { "internalType": "uint256", "name": "startTime", "type": "uint256" }, { "internalType": "uint256", "name": "endTime", "type": "uint256" }, { "internalType": "uint256", "name": "highestBid", "type": "uint256" }, { "internalType": "address", "name": "highestBidder", "type": "address" }, { "internalType": "bool", "name": "ended", "type": "bool" }, { "internalType": "address", "name": "winner", "type": "address" }], "internalType": "struct PlayerAuction.Auction", "name": "", "type": "tuple" }], "stateMutability": "view", "type": "function" },
  { "inputs": [{ "internalType": "uint256", "name": "_limit", "type": "uint256" }], "name": "getPlayerList", "outputs": [{ "components": [{ "internalType": "uint256", "name": "id", "type": "uint256" }, { "internalType": "string", "name": "name", "type": "string" }, { "internalType": "string", "name": "position", "type": "string" }, { "internalType": "uint256", "name": "basePrice", "type": "uint256" }, { "internalType": "address", "name": "currentClub", "type": "address" }, { "internalType": "bool", "name": "auctioned", "type": "bool" }], "internalType": "struct PlayerAuction.Player[]", "name": "", "type": "tuple[]" }], "stateMutability": "view", "type": "function" },
  { "inputs": [{ "internalType": "string", "name": "_name", "type": "string" }, { "internalType": "string", "name": "_position", "type": "string" }, { "internalType": "uint256", "name": "_basePrice", "type": "uint256" }], "name": "registerPlayer", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [{ "internalType": "uint256", "name": "_playerId", "type": "uint256" }, { "internalType": "uint256", "name": "_auctionDuration", "type": "uint256" }], "name": "createAuction", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [{ "internalType": "uint256", "name": "_auctionId", "type": "uint256" }], "name": "placeBid", "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }], "stateMutability": "payable", "type": "function" },
  { "inputs": [{ "internalType": "uint256", "name": "_auctionId", "type": "uint256" }], "name": "endAuction", "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [], "name": "withdraw", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "stateMutability": "payable", "type": "receive" }
];
